"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

from celery.schedules import crontab
from dotenv import load_dotenv


# =========================================================
# BASE DIRECTORY
# =========================================================

BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")


# =========================================================
# SECURITY
# =========================================================

SECRET_KEY = os.getenv('SECRET_KEY')

DEBUG = os.getenv('DEBUG') == 'True'

# Change this in production
ALLOWED_HOSTS = [
    'job-tracker-api-c9tu.onrender.com',
    'localhost',
    '127.0.0.1',
]

# =========================================================
# APPLICATIONS
# =========================================================

INSTALLED_APPS = [
    # Django Apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Local Apps
    'core.apps.CoreConfig',

    # Third Party Apps
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'django_filters',
    'drf_spectacular',
    'drf_spectacular_sidecar',
    'django_celery_beat',
]


# =========================================================
# MIDDLEWARE
# =========================================================

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    # Custom Middleware
    'core.middleware.APILogMiddleware',
]


# =========================================================
# ROOT URLS / WSGI
# =========================================================

ROOT_URLCONF = 'config.urls'

WSGI_APPLICATION = 'config.wsgi.application'


# =========================================================
# TEMPLATES
# =========================================================

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',

        'DIRS': [],

        'APP_DIRS': True,

        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# =========================================================
# DATABASE
# =========================================================

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',

        'NAME': os.getenv('DB_NAME'),

        'USER': os.getenv('DB_USER'),

        'PASSWORD': os.getenv('DB_PASSWORD'),

        'HOST': os.getenv('DB_HOST', 'localhost'),

        'PORT': os.getenv('DB_PORT', '5432'),
    }
}


# =========================================================
# CUSTOM USER MODEL
# =========================================================

AUTH_USER_MODEL = 'core.User'


# =========================================================
# PASSWORD VALIDATION
# =========================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME':
            'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME':
            'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME':
            'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME':
            'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# =========================================================
# INTERNATIONALIZATION
# =========================================================

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# =========================================================
# STATIC & MEDIA FILES
# =========================================================

STATIC_URL = 'static/'

STATIC_ROOT = BASE_DIR / 'staticfiles'

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MEDIA_URL = '/media/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# =========================================================
# DJANGO REST FRAMEWORK
# =========================================================

REST_FRAMEWORK = {

    # Authentication
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),

    # OpenAPI / Swagger
    'DEFAULT_SCHEMA_CLASS':
        'drf_spectacular.openapi.AutoSchema',

    # Filtering
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
    ),

    # Pagination
    'DEFAULT_PAGINATION_CLASS':
        'rest_framework.pagination.PageNumberPagination',

    'PAGE_SIZE': 10,

    # Throttling
    'DEFAULT_THROTTLE_CLASSES': [ ],

    'DEFAULT_THROTTLE_RATES': {

        # Authenticated users
        'user': '1000/day',

        # OTP send protection
        'send_otp': '3/min',

        # OTP verification protection
        'verify_otp': '10/min',

        # Login brute-force protection
        'login': '10/min',
    },

    # Custom Exception Handler
    'EXCEPTION_HANDLER':
        'core.exceptions.custom_exception_handler',
}


# =========================================================
# SIMPLE JWT
# =========================================================

SIMPLE_JWT = {

    'ACCESS_TOKEN_LIFETIME':
        timedelta(minutes=60),

    'REFRESH_TOKEN_LIFETIME':
        timedelta(days=1),

    'AUTH_HEADER_TYPES':
        ('Bearer',),

    'BLACKLIST_AFTER_ROTATION':
        True,

    'ROTATE_REFRESH_TOKENS':
        True,
}


# =========================================================
# REDIS CACHE
# =========================================================

CACHES = {
    "default": {

        "BACKEND":
            "django_redis.cache.RedisCache",

        "LOCATION":
            os.getenv(
                "REDIS_URL",
                "redis://127.0.0.1:6379/0"
            ),

        "OPTIONS": {

            "CLIENT_CLASS":
                "django_redis.client.DefaultClient",

            "SOCKET_CONNECT_TIMEOUT":
                5,

            "SOCKET_TIMEOUT":
                5,

            "RETRY_ON_TIMEOUT":
                True,

            "CONNECTION_POOL_KWARGS": {
                "max_connections": 50,
                "ssl_cert_reqs": None  # Disable SSL certificate verification
            },
        },

        "KEY_PREFIX":
            "jobtracker",

        "TIMEOUT":
            300,

        "VERSION":
            1,
    }
}


# =========================================================
# CELERY
# =========================================================

CELERY_BROKER_URL = os.getenv("REDIS_URL")
CELERY_BROKER_TRANSPORT_OPTIONS = {"ssl_cert_reqs": None}  # required for Upstash TLS

CELERY_ACCEPT_CONTENT = ['json']

CELERY_TASK_SERIALIZER = 'json'

CELERY_BEAT_SCHEDULE = {

    'send-reminders-every-minute': {

        'task':
            'core.tasks.send_reminders',

        'schedule':
            60.0,
    },

    'cleanup-old-otps': {

        'task':
            'core.tasks.cleanup_old_otps',

        'schedule':
            crontab(hour=0, minute=0),
    },

    'cleanup-old-api-logs': {

        'task':
            'core.tasks.cleanup_old_api_logs',

        'schedule':
            crontab(hour=1, minute=0),
    },
}


# =========================================================
# SECURITY SETTINGS
# =========================================================

SECURE_BROWSER_XSS_FILTER = True

SECURE_CONTENT_TYPE_NOSNIFF = True


# =========================================================
# EMAIL CONFIGURATION
# =========================================================

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

EMAIL_HOST = 'smtp.gmail.com'

EMAIL_PORT = 587

EMAIL_USE_TLS = True

EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")

EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")


# =========================================================
# DRF SPECTACULAR / SWAGGER
# =========================================================

SPECTACULAR_SETTINGS = {

    'TITLE':
        'Job Tracker API',

    'DESCRIPTION': """
    Production-ready Job Tracker and Application Management Backend API.

    Features:
    - JWT Authentication
    - OTP Email Verification
    - Job Application Tracking
    - Resume/File Uploads
    - Redis + Celery Background Tasks
    - Reminder Scheduling
    - Secure Token Rotation
    """,

    'VERSION':
        '1.0.0',

    'SERVE_INCLUDE_SCHEMA':
        False,

    # Swagger UI
    'SWAGGER_UI_SETTINGS': {

        'deepLinking':
            True,

        'persistAuthorization':
            True,

        'displayRequestDuration':
            True,
    },

    # Better request/response separation
    'COMPONENT_SPLIT_REQUEST':
        True,

    # JWT Authentication
    'APPEND_COMPONENTS': {

        'securitySchemes': {

            'BearerAuth': {

                'type':
                    'http',

                'scheme':
                    'bearer',

                'bearerFormat':
                    'JWT',
            }
        }
    },

    'SECURITY': [
        {
            'BearerAuth': []
        }
    ],

    # Professional sorting
    'SORT_OPERATIONS':
        True,

    'SORT_TAGS':
        True,
}